// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blockchain/block_chain.proto

/*
Package blockchain is a generated protocol buffer package.

It is generated from these files:
	blockchain/block_chain.proto

It has these top-level messages:
	Id
	Chaininfo
	EmptyMsg
	TransactionHeader
	Transaction
	TransactionList
	BlockHeader
	Block
*/
package blockchain

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Id struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Id) Reset()                    { *m = Id{} }
func (m *Id) String() string            { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()               {}
func (*Id) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Id) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Chaininfo struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Height int32  `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
}

func (m *Chaininfo) Reset()                    { *m = Chaininfo{} }
func (m *Chaininfo) String() string            { return proto.CompactTextString(m) }
func (*Chaininfo) ProtoMessage()               {}
func (*Chaininfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Chaininfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Chaininfo) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type EmptyMsg struct {
}

func (m *EmptyMsg) Reset()                    { *m = EmptyMsg{} }
func (m *EmptyMsg) String() string            { return proto.CompactTextString(m) }
func (*EmptyMsg) ProtoMessage()               {}
func (*EmptyMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type TransactionHeader struct {
	Nonce string `protobuf:"bytes,1,opt,name=nonce" json:"nonce,omitempty"`
	Txid  string `protobuf:"bytes,2,opt,name=txid" json:"txid,omitempty"`
	Type  string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
}

func (m *TransactionHeader) Reset()                    { *m = TransactionHeader{} }
func (m *TransactionHeader) String() string            { return proto.CompactTextString(m) }
func (*TransactionHeader) ProtoMessage()               {}
func (*TransactionHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TransactionHeader) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *TransactionHeader) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *TransactionHeader) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Transaction struct {
	Id              string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Header          []byte `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	HeaderSignature string `protobuf:"bytes,3,opt,name=header_signature,json=headerSignature" json:"header_signature,omitempty"`
	Payload         []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetHeader() []byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Transaction) GetHeaderSignature() string {
	if m != nil {
		return m.HeaderSignature
	}
	return ""
}

func (m *Transaction) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type TransactionList struct {
	Transactions []*Transaction `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *TransactionList) Reset()                    { *m = TransactionList{} }
func (m *TransactionList) String() string            { return proto.CompactTextString(m) }
func (*TransactionList) ProtoMessage()               {}
func (*TransactionList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TransactionList) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type BlockHeader struct {
	Height            int32  `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	PreviousBlockHash string `protobuf:"bytes,2,opt,name=previous_block_hash,json=previousBlockHash" json:"previous_block_hash,omitempty"`
	TransactionCount  int32  `protobuf:"varint,3,opt,name=transaction_count,json=transactionCount" json:"transaction_count,omitempty"`
	Version           int32  `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
	Timestamp         int32  `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	StateRootHash     string `protobuf:"bytes,6,opt,name=state_root_hash,json=stateRootHash" json:"state_root_hash,omitempty"`
}

func (m *BlockHeader) Reset()                    { *m = BlockHeader{} }
func (m *BlockHeader) String() string            { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()               {}
func (*BlockHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BlockHeader) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockHeader) GetPreviousBlockHash() string {
	if m != nil {
		return m.PreviousBlockHash
	}
	return ""
}

func (m *BlockHeader) GetTransactionCount() int32 {
	if m != nil {
		return m.TransactionCount
	}
	return 0
}

func (m *BlockHeader) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BlockHeader) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockHeader) GetStateRootHash() string {
	if m != nil {
		return m.StateRootHash
	}
	return ""
}

type Block struct {
	Header          []byte         `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	HeaderSignature string         `protobuf:"bytes,2,opt,name=header_signature,json=headerSignature" json:"header_signature,omitempty"`
	Transactions    []*Transaction `protobuf:"bytes,3,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Block) GetHeader() []byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetHeaderSignature() string {
	if m != nil {
		return m.HeaderSignature
	}
	return ""
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterType((*Id)(nil), "blockchain.Id")
	proto.RegisterType((*Chaininfo)(nil), "blockchain.Chaininfo")
	proto.RegisterType((*EmptyMsg)(nil), "blockchain.EmptyMsg")
	proto.RegisterType((*TransactionHeader)(nil), "blockchain.TransactionHeader")
	proto.RegisterType((*Transaction)(nil), "blockchain.Transaction")
	proto.RegisterType((*TransactionList)(nil), "blockchain.TransactionList")
	proto.RegisterType((*BlockHeader)(nil), "blockchain.BlockHeader")
	proto.RegisterType((*Block)(nil), "blockchain.Block")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BlockChain service

type BlockChainClient interface {
	GetChaininfo(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*Chaininfo, error)
	GetTransaction(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Transaction, error)
}

type blockChainClient struct {
	cc *grpc.ClientConn
}

func NewBlockChainClient(cc *grpc.ClientConn) BlockChainClient {
	return &blockChainClient{cc}
}

func (c *blockChainClient) GetChaininfo(ctx context.Context, in *EmptyMsg, opts ...grpc.CallOption) (*Chaininfo, error) {
	out := new(Chaininfo)
	err := grpc.Invoke(ctx, "/blockchain.BlockChain/GetChaininfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockChainClient) GetTransaction(ctx context.Context, in *Id, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := grpc.Invoke(ctx, "/blockchain.BlockChain/GetTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BlockChain service

type BlockChainServer interface {
	GetChaininfo(context.Context, *EmptyMsg) (*Chaininfo, error)
	GetTransaction(context.Context, *Id) (*Transaction, error)
}

func RegisterBlockChainServer(s *grpc.Server, srv BlockChainServer) {
	s.RegisterService(&_BlockChain_serviceDesc, srv)
}

func _BlockChain_GetChaininfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockChainServer).GetChaininfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.BlockChain/GetChaininfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockChainServer).GetChaininfo(ctx, req.(*EmptyMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockChain_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockChainServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockchain.BlockChain/GetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockChainServer).GetTransaction(ctx, req.(*Id))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlockChain_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blockchain.BlockChain",
	HandlerType: (*BlockChainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetChaininfo",
			Handler:    _BlockChain_GetChaininfo_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _BlockChain_GetTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blockchain/block_chain.proto",
}

func init() { proto.RegisterFile("blockchain/block_chain.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 529 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0x9d, 0x3a, 0x90, 0x49, 0xda, 0x34, 0x9b, 0x00, 0x26, 0xe4, 0x10, 0xf9, 0x80, 0x82,
	0x10, 0x36, 0x2a, 0x07, 0x0e, 0xdc, 0x52, 0xa1, 0x52, 0x09, 0x50, 0x30, 0xbd, 0x47, 0x5b, 0x7b,
	0xb1, 0x57, 0xc4, 0xbb, 0x96, 0x77, 0x53, 0x35, 0x20, 0x2e, 0x5c, 0x78, 0x00, 0x5e, 0x85, 0x37,
	0xe1, 0x0d, 0x10, 0x0f, 0x82, 0x3c, 0xb6, 0xf1, 0xb6, 0x02, 0x21, 0x6e, 0x33, 0xdf, 0xcc, 0x7e,
	0xf3, 0xcd, 0xcf, 0xc2, 0xec, 0x7c, 0x23, 0xa3, 0xf7, 0x51, 0x4a, 0xb9, 0x08, 0xd0, 0x5c, 0xa3,
	0xed, 0xe7, 0x85, 0xd4, 0x92, 0x40, 0x1b, 0x9d, 0xce, 0x12, 0x29, 0x93, 0x0d, 0x0b, 0x68, 0xce,
	0x03, 0x2a, 0x84, 0xd4, 0x54, 0x73, 0x29, 0x54, 0x95, 0xe9, 0x4d, 0xc0, 0x3e, 0x8d, 0xc9, 0x01,
	0xd8, 0x3c, 0x76, 0xad, 0xb9, 0xb5, 0xe8, 0x85, 0x36, 0x8f, 0xbd, 0xa7, 0xd0, 0x3b, 0x2e, 0x1f,
	0x73, 0xf1, 0x4e, 0x12, 0x02, 0x7b, 0x82, 0x66, 0xac, 0x0e, 0xa3, 0x4d, 0x6e, 0x43, 0x37, 0x65,
	0x3c, 0x49, 0xb5, 0x6b, 0xcf, 0xad, 0x85, 0x13, 0xd6, 0x9e, 0x07, 0x70, 0xf3, 0x79, 0x96, 0xeb,
	0xdd, 0x2b, 0x95, 0x78, 0x6f, 0x60, 0x74, 0x56, 0x50, 0xa1, 0x68, 0x54, 0x16, 0x7c, 0xc1, 0x68,
	0xcc, 0x0a, 0x32, 0x01, 0x47, 0x48, 0x11, 0x35, 0x6c, 0x95, 0x53, 0x96, 0xd0, 0x97, 0x3c, 0x46,
	0xb2, 0x5e, 0x88, 0x36, 0x62, 0xbb, 0x9c, 0xb9, 0x9d, 0x1a, 0xdb, 0xe5, 0xcc, 0xfb, 0x00, 0x7d,
	0x83, 0xf2, 0xba, 0xec, 0x4a, 0x55, 0x59, 0x06, 0x89, 0x06, 0x61, 0xed, 0x91, 0x07, 0x70, 0x58,
	0x59, 0x6b, 0xc5, 0x13, 0x41, 0xf5, 0xb6, 0x68, 0x68, 0x87, 0x15, 0xfe, 0xb6, 0x81, 0x89, 0x0b,
	0x37, 0x72, 0xba, 0xdb, 0x48, 0x1a, 0xbb, 0x7b, 0xc8, 0xd1, 0xb8, 0xde, 0x6b, 0x18, 0x1a, 0xb5,
	0x5f, 0x72, 0xa5, 0xc9, 0x33, 0x18, 0xe8, 0x16, 0x52, 0xae, 0x35, 0xef, 0x2c, 0xfa, 0x47, 0x77,
	0xfc, 0x76, 0xfa, 0xbe, 0xf1, 0x24, 0xbc, 0x92, 0xec, 0xfd, 0xb0, 0xa0, 0xbf, 0x2c, 0x13, 0xeb,
	0xc9, 0xb4, 0x23, 0xb5, 0xcc, 0x91, 0x12, 0x1f, 0xc6, 0x79, 0xc1, 0x2e, 0xb8, 0xdc, 0xaa, 0x75,
	0xb5, 0xe9, 0x94, 0xaa, 0xb4, 0x1e, 0xd5, 0xa8, 0x09, 0x55, 0x4c, 0x54, 0xa5, 0xe4, 0x21, 0x8c,
	0x8c, 0x3a, 0xeb, 0x48, 0x6e, 0x85, 0xc6, 0x6e, 0x9d, 0xf0, 0xd0, 0x08, 0x1c, 0x97, 0x78, 0xd9,
	0xee, 0x05, 0x2b, 0x14, 0x97, 0x02, 0xdb, 0x75, 0xc2, 0xc6, 0x25, 0x33, 0xe8, 0x69, 0x9e, 0x31,
	0xa5, 0x69, 0x96, 0xbb, 0x0e, 0xc6, 0x5a, 0x80, 0xdc, 0x87, 0xa1, 0xd2, 0x54, 0xb3, 0x75, 0x21,
	0xa5, 0xae, 0x04, 0x75, 0x51, 0xd0, 0x3e, 0xc2, 0xa1, 0x94, 0xba, 0x14, 0xe3, 0x7d, 0xb1, 0xc0,
	0x41, 0x69, 0xc6, 0x6e, 0xac, 0x7f, 0xee, 0xc6, 0xfe, 0xf3, 0x6e, 0xae, 0x8f, 0xbb, 0xf3, 0x1f,
	0xe3, 0x3e, 0xfa, 0x66, 0x01, 0xa0, 0x12, 0x3c, 0x6c, 0xb2, 0x82, 0xc1, 0x09, 0xd3, 0xed, 0x91,
	0x4f, 0x4c, 0x96, 0xe6, 0x84, 0xa7, 0xb7, 0x4c, 0xf4, 0x77, 0xb2, 0x37, 0xfe, 0xfc, 0xfd, 0xe7,
	0x57, 0x7b, 0x9f, 0xf4, 0x03, 0x8c, 0x3c, 0x42, 0x86, 0x33, 0x38, 0x38, 0x61, 0xfa, 0xca, 0x79,
	0x9a, 0xaf, 0x4f, 0xe3, 0xe9, 0xdf, 0x94, 0x7a, 0x77, 0x91, 0x6f, 0x4c, 0x46, 0x81, 0x21, 0x39,
	0xf8, 0xc8, 0xe3, 0x4f, 0xcb, 0xc7, 0x70, 0x8f, 0x4b, 0x3f, 0x29, 0xf2, 0xc8, 0x67, 0x97, 0x34,
	0xcb, 0x37, 0x4c, 0x19, 0x2c, 0xcb, 0x61, 0xdb, 0xd2, 0xaa, 0xfc, 0xcf, 0x2b, 0xeb, 0xbc, 0x8b,
	0x1f, 0xfb, 0xc9, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x2a, 0xa9, 0x58, 0x22, 0x04, 0x00,
	0x00,
}
